# Lab0 Exercise 4 Numpy Array Operations

In [ ]:
import numpy as np
matrix = np.ones((5,5), dtype = int)
matrix[1:-1,1:-1] = 0
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np
np.random.seed(42)
randomData = np.random.randn(100,3)

mean = randomData.mean(axis=0)
std = randomData.std(axis=0)

normalizeData = (randomData - mean)/std

print("Mean: ", normalizeData.mean(axis=0))
print("Std: ", normalizeData.std(axis=0))

Mean:  [-2.60902411e-17  1.55431223e-17 -8.88178420e-18]
Std:  [1. 1. 1.]


In [ ]:
import numpy as np

X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1

X_b = np.c_[np.ones((X.shape[0], 1)), X]

true_theta_b = np.r_[0, true_theta]

theta_hat = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

print("Estimated coefficients:", theta_hat)
print("True theta:", true_theta_b)

Estimated coefficients: [-0.01035573  2.51756955 -1.19800274  3.72573182]
True theta: [ 0.   2.5 -1.2  3.7]
